### ISSUE TITLE
EmGenderCellListener

### ISSUE THREAD

**Issue by niko-balanis** [FJD-CEPH/aCNViewer#3]
Not sure I know what to do about this error. Tryinig to load 5 files. What would be nice is to know which cel file threw the error. I will go code sleuthing but hoping you have encountered these issues before.

Nikolas Balanis

Opening layout file: /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.cdf
Reading 1856069 probesets.........................................Done. (0.2 min)
Kept 909622 probesets.
Reading and pre-processing 5 cel files.....
**FATAL ERROR:EmGenderCelListener::fillInContrastValues() - Warning. alleleMedian() failed for probeset: SNP_A-1780803**
  File "/home/graeberlab/bin/aCNViewer/code/commandLineUtils.py", line 162, in runFromTerminal
    mainFunctionToRun(options, args)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 6769, in run
    useCustomPloidies=options.useCustomPloidies)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 6035, in process
    byChr, pattern, samplePairFile, useCustomPloidies)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 5702, in __getAscatFileAndDumpFileName
    *paramList)
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 273, in getFunctionResultWithCache
    res = functionName(*args)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 1564, in process
    libDir, gw6Dir, platform, targetDir)
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 273, in getFunctionResultWithCache
    res = functionName(*args)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 1138, in _runPennCnvAndGetLrrBafFile
    cmd], os.path.join(targetDir, 'step1.1'))
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 181, in _runFunc
    func(*argList)
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 308, in mySystem
    cmd, code, os.environ.get('HOSTNAME', '?')))
<type 'exceptions.NotImplementedError'>: cmd "/home/graeberlab/bin/aCNViewer_DATA/bin/apt-1.18.2-x86_64-intel-linux/bin/apt-probeset-genotype -c /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.cdf -a birdseed --read-models-birdseed /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.birdseed.models --special-snps /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.specialSNPs --out-dir /media/graeberlab/wdblack/CNLOH/top_output/tmp/apt_out --cel-files /media/graeberlab/wdblack/CNLOH/top_output/tmp/list.nsp" failed with code 65280 on host ?
Traceback (most recent call last):
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 7220, in <module>
    width')], run)
  File "/home/graeberlab/bin/aCNViewer/code/commandLineUtils.py", line 162, in runFromTerminal
    mainFunctionToRun(options, args)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 6769, in run
    useCustomPloidies=options.useCustomPloidies)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 6035, in process
    byChr, pattern, samplePairFile, useCustomPloidies)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 5702, in __getAscatFileAndDumpFileName
    *paramList)
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 273, in getFunctionResultWithCache
    res = functionName(*args)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 1564, in process
    libDir, gw6Dir, platform, targetDir)
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 273, in getFunctionResultWithCache
    res = functionName(*args)
  File "/home/graeberlab/bin/aCNViewer/code/aCNViewer.py", line 1138, in _runPennCnvAndGetLrrBafFile
    cmd], os.path.join(targetDir, 'step1.1'))
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 181, in _runFunc
    func(*argList)
  File "/home/graeberlab/bin/aCNViewer/code/Utilities.py", line 308, in mySystem
    cmd, code, os.environ.get('HOSTNAME', '?')))
NotImplementedError: cmd "/home/graeberlab/bin/aCNViewer_DATA/bin/apt-1.18.2-x86_64-intel-linux/bin/apt-probeset-genotype -c /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.cdf -a birdseed --read-models-birdseed /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.birdseed.models --special-snps /media/graeberlab/wdblack/CNLOH/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.specialSNPs --out-dir /media/graeberlab/wdblack/CNLOH/top_output/tmp/apt_out --cel-files /media/graeberlab/wdblack/CNLOH/top_output/tmp/list.nsp" failed with code 65280 on host ?

**Comment by niko-balanis** [comment]
Edit: I found this link. Would it be possible to put the gender calling option of apt powertools into aCNViewer or is there some way to do it simply ? I feel its likely ill have to modify the code myself. But in case I am missing something and for those who thought id ask. Thanks. Btw the software is awesome.


http://seqanswers.com/forums/showthread.php?t=45304

For future reference, I ran into this same problem (with a different array) when calling the Affymetrix Power Tools "apt-probeset-genotype" v1.6.10 http://www.affymetrix.com/estore/sup...F14CBECCE0D887. The problem was that I was trying to force the genders by invoking the "--read-genders" option, thus bypassing the gender calling methods by explicitly providing sample genders. When I removed this flag and reverted to the "--set-gender-method cn-probe-chrXY-ratio" option, this alleleMedian() error goes away.

**Comment by niko-balanis** [comment]
thing s like --no-gender-force also dont help. THe real problem is that you cannot tell which sample is throwing the error. I guess I could put each file in a different folder and for loop it but feels hacky.

**Comment by FJD-CEPH** [comment]
I can add any option(s) needed. For that, I would need to reproduce the error here. Are the SNP array data you are using public? If so, could you please provide me with the references so that I can get access to these data?

**Comment by niko-balanis** [comment]
I sent a google drive link by email to the account owner email.

**Comment by FJD-CEPH** [comment]
I tried various options to try to get rid of that error but no success so far so I will add an option to automatically remove samples that fail in the next release.
