### ISSUE TITLE
Error running test with docker installation

### ISSUE THREAD

**Issue by FriederikeHanssen** [FJD-CEPH/aCNViewer#6]
### Command run

When pulling the docker image with 

`docker pull  fjdceph/acnviewer` 

and then run 

`docker run fjdceph/acnviewer -P testAll -t .` 

I get the following output:

###  Error message

```
ERROR in thread:  File "/data/aCNViewer/code/Cluster.py", line 94, in run
    self._res = self.__func(*self._args)
  File "/data/aCNViewer/code/Utilities.py", line 308, in mySystem
    cmd, code, os.environ.get('HOSTNAME', '?')))
<type 'exceptions.NotImplementedError'>: cmd "/usr/bin/python /data/aCNViewer/code/aCNViewer.py -f aCNViewer_DATA/wes/bams/ -t ./TEST_WES_RAW --refBuild hg19 -w 2000000 -b aCNViewer_DATA/bin --fileType Sequenza --samplePairFile aCNViewer_DATA/wes/bams/sampleFile.txt -n 4 1> ./TEST_WES_RAW.out 2> ./TEST_WES_RAW.err && touch ./TEST_WES_RAW_done" failed with code 256 on host 95876361d8d8
  File "/data/aCNViewer/code/commandLineUtils.py", line 162, in runFromTerminal
    mainFunctionToRun(options, args)
  File "aCNViewer/code/aCNViewer.py", line 6806, in run
    options.binDir, options.dirName)
  File "aCNViewer/code/aCNViewer.py", line 6379, in process
    ProcessFileFromCluster()._runCmdList(cmdList2, None, cluster)
  File "/data/aCNViewer/code/annovar.py", line 407, in _runCmdList
    optionList=optionList)
  File "/data/aCNViewer/code/Cluster.py", line 241, in submitJobAndGetId
    self.submit(Utilities.mySystem, command, scriptName)
  File "/data/aCNViewer/code/Cluster.py", line 207, in submit
    self.__waitForThreadToFinish()
  File "/data/aCNViewer/code/Cluster.py", line 199, in __waitForThreadToFinish
    if self.__canNewThreadBeCreated():
  File "/data/aCNViewer/code/Cluster.py", line 185, in __canNewThreadBeCreated
    self.__removeFinishedJobs()
  File "/data/aCNViewer/code/Cluster.py", line 150, in __removeFinishedJobs
    raise NotImplementedError
<type 'exceptions.NotImplementedError'>:
    options.binDir, options.dirName)
  File "aCNViewer/code/aCNViewer.py", line 6379, in process
    ProcessFileFromCluster()._runCmdList(cmdList2, None, cluster)
  File "/data/aCNViewer/code/annovar.py", line 407, in _runCmdList
    optionList=optionList)
  File "/data/aCNViewer/code/Cluster.py", line 241, in submitJobAndGetId
    self.submit(Utilities.mySystem, command, scriptName)
  File "/data/aCNViewer/code/Cluster.py", line 207, in submit
    self.__waitForThreadToFinish()
  File "/data/aCNViewer/code/Cluster.py", line 199, in __waitForThreadToFinish
    if self.__canNewThreadBeCreated():
  File "/data/aCNViewer/code/Cluster.py", line 185, in __canNewThreadBeCreated
    self.__removeFinishedJobs()
  File "/data/aCNViewer/code/Cluster.py", line 150, in __removeFinishedJobs
    raise NotImplementedError
NotImplementedError  cmd "/usr/bin/python /data/aCNViewer/code/aCNViewer.py -f aCNViewer_DATA/wes/bams/ -t ./TEST_WES_RAW2 --refBuild hg19 -w 2000000 -b aCNViewer_DATA/bin --fileType Sequenza --samplePairFile aCNViewer_DATA/wes/bams/sampleFile.txt -n 4 --useCustomPloidies 0 1> ./TEST_WES_RAW2.out 2> ./TEST_WES_RAW2.err && touch ./TEST_WES_RAW2_done" failed with code 256 on host 95876361d8d8

```

Attached there is the complete console output in case this is useful. 
[error_acnviewer.log](https://github.com/FJD-CEPH/aCNViewer/files/5150531/error_acnviewer.log)
### Docker version

19.03.12

**Comment by FriederikeHanssen** [comment]
Update: 
I got it to run by re-building the container and changing the base image:

```
# Pull base image.
FROM ubuntu:18.04
```

and throwing lots of storage at it during the build process. 

However, running the tests caused 4 failures:
```
testAffy (__main__.TestACNViewer2) ... ok
testAffyCel (__main__.TestACNViewer2) ... FAIL
testAffyCel2 (__main__.TestACNViewer2) ... FAIL
testAffyChr (__main__.TestACNViewer2) ... ok
testAffyDendro (__main__.TestACNViewer2) ... ok
testAffyGenPos (__main__.TestACNViewer2) ... ok
testAffyGistic (__main__.TestACNViewer2) ... ok
testAffyHeatmap1 (__main__.TestACNViewer2) ... ok
testAffyHeatmap2 (__main__.TestACNViewer2) ... ok
testAffyJpg (__main__.TestACNViewer2) ... ok
testAffyOtherOut (__main__.TestACNViewer2) ... ok
testAffyPdf (__main__.TestACNViewer2) ... ok
testAffyRcolor (__main__.TestACNViewer2) ... ok
testDefaultPloidy (__main__.TestACNViewer2) ... ok
testIllu (__main__.TestACNViewer2) ... ok
testPennCNV (__main__.TestACNViewer2) ... ok
testPercent (__main__.TestACNViewer2) ... ok
testSampleToExcludeList (__main__.TestACNViewer2) ... ok
testSampleToExcludeList2 (__main__.TestACNViewer2) ... ok
testSampleToProcessList (__main__.TestACNViewer2) ... ok
testSampleToProcessList2 (__main__.TestACNViewer2) ... ok
testWesRaw (__main__.TestACNViewer2) ... FAIL
testWesRaw2 (__main__.TestACNViewer2) ... FAIL
testWesSequenza (__main__.TestACNViewer2) ... ok

======================================================================
FAIL: testAffyCel (__main__.TestACNViewer2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "aCNViewer/code/aCNViewer.py", line 6587, in testAffyCel
    self.__testAffyCel('TEST_AFFY_CEL', 0.17063517003915474)#0.1706368610472045)
  File "aCNViewer/code/aCNViewer.py", line 6584, in __testAffyCel
    expectedPloidy)
AssertionError: 0.17063611915988175 != 0.17063517003915474

======================================================================
FAIL: testAffyCel2 (__main__.TestACNViewer2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "aCNViewer/code/aCNViewer.py", line 6590, in testAffyCel2
    self.__testAffyCel('TEST_AFFY_CEL2', 0.1723724692407916)#0.17237363749618306)
  File "aCNViewer/code/aCNViewer.py", line 6584, in __testAffyCel
    expectedPloidy)
AssertionError: 0.17237337013408213 != 0.1723724692407916

======================================================================
FAIL: testWesRaw (__main__.TestACNViewer2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "aCNViewer/code/aCNViewer.py", line 6646, in testWesRaw
    self.__testWesRaw('TEST_WES_RAW', 0.005251378143962131)
  File "aCNViewer/code/aCNViewer.py", line 6635, in __testWesRaw
    outDir = self.__testBase(testName, 1)
  File "aCNViewer/code/aCNViewer.py", line 6440, in __testBase
    self.assertFalse(os.path.isdir(os.path.join(outDir, 'tmp')))
AssertionError: True is not false

======================================================================
FAIL: testWesRaw2 (__main__.TestACNViewer2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "aCNViewer/code/aCNViewer.py", line 6649, in testWesRaw2
    self.__testWesRaw('TEST_WES_RAW2', 0.009361568085369818)
  File "aCNViewer/code/aCNViewer.py", line 6635, in __testWesRaw
    outDir = self.__testBase(testName, 1)
  File "aCNViewer/code/aCNViewer.py", line 6440, in __testBase
    self.assertFalse(os.path.isdir(os.path.join(outDir, 'tmp')))
AssertionError: True is not false

----------------------------------------------------------------------
Ran 24 tests in 1.793s

FAILED (failures=4)
y/Projects/aCNViewer/test_results/TEST_AFFY_HEATMAP1': None, '
aCNViewer/test_results/TEST_AFFY_HEATMAP2': None, 'aCNViewer/test_results/TEST_SAMPLE_TO_PROCESS': None}
/usr/bin/python /data/aCNViewer/code/aCNViewer.py -f aCNViewer_DATA/snpArrayIllu660k/GSE47357_Matrix_signal_660w.txt.gz -t /aCNViewer/test_results/TEST_ILLU --refBuild hg19 -w 2000000 -b aCNViewer_DATA/bin --probeFile aCNViewer_DATA/snpArrayIllu660k/Human660W-Quad_v1_H_SNPlist.txt --platform Illumina660k --beadchip "human660w-quad" 1> /aCNViewer/test_results/TEST_ILLU.out 2> /aCNViewer/test_results/TEST_ILLU.err && touch /aCNViewer/test_results/TEST_ILLU_done
TEST_AFFY_GISTIC skipped in fast test mode
```

**Comment by FJD-CEPH** [comment]
Thank you for reporting the issue. I am a bit busy this week so I will get back to you next week (let's say middle of the week) with a fix as the unit tests failed but only due to very small differences. I will also try to add a singularity image for aCNViewer which will replace the docker version and which should provide an easier way to use aCNViewer.

**Comment by FriederikeHanssen** [comment]
Sound great :) Looking forward to throw my data in the tool. Singularity would be great to have too. Although, we have just converted docker images with singularity so far and that has worked fine. Haven't tried with this tool though :)

**Comment by FriederikeHanssen** [comment]
Hi @FJD-CEPH ! I have another question: I ran my samples with GRCh38. If I understand the readme correctly, I have to add this to `BUILD` somehow, because currently `hg18` and `hg19` are supported, right? I don't quite get how I can do this to a build docker image? 
Also do you plan to package this to conda at some point?

Thank you for your help :)

**Comment by FJD-CEPH** [comment]
Hello @FriederikeHanssen, I need to make more changes than anticipated to account for the obsolesence of python2 and I will also adjust a little bit the code so that it is compatible with newer version of R (BiocManager::install instead of biocLite). I will get back to you as soon as I can with a brand new version (I will also integrate hg38 files as a bonus !).

**Comment by FriederikeHanssen** [comment]
Hey @FJD-CEPH ! 
Thank you for your hard work on this tool and for creating new images 😇 ! I was wondering whether you can provide a rough estimate as to when you find time for this. This would help me plan my own projects around the time when I can run your tool. 😊

**Comment by FriederikeHanssen** [comment]
Hi!
So I kept playing around with docker. So far, I have not been able to create the docker image. What I have been able to do is, to create a conda environment with all the dependencies, as well as using `hg38`. I have build docker containers based on conda in the past, so I am hoping this is also possible here. In case conda is useful to you or anyone else, I will add the `environment.yml` here. `GISTIC` is made available in the `aCNViewer_DATA` folder. However, unfortunately this can then only be run on a linux based system. (At least I didn't get it to run on MacOS and my own installation of `GISTIC` was not accepted by the program).

```
# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: fhanssen-acnviewer-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7
  - conda-forge::r-base=4.0.2 
  - conda-forge::r-ggplot2=3.3.2 
  - conda-forge::r-gplots=3.1.0 
  - conda-forge::r-plotrix=3.7
  - conda-forge::r-rcurl=1.98_1_2 
  - bioconda::bioconductor-limma=3.44.1 
  - conda-forge::xorg-libx11=1.6.12
  
  - bioconda::samtools=1.10 
  - bioconda::ascat=2.5.2
  - bioconda::sequenza-utils=3.0.0
  - bioconda::r-sequenza=3.0.0
  - conda-forge::r-squash=1.0.9
  - bioconda::bioconductor-copynumber=1.28.0 
  - bioconda::bioconductor-cghregions=1.46.0 

  - conda-forge::r-glue=1.4.2 
  - conda-forge::r-rlang=0.4.7 
  - conda-forge::r-pkgconfig=2.0.3 
  - conda-forge::r-ellipsis=0.3.1 
  - conda-forge::r-vctrs=0.3.4
  - conda-forge::r-hms=0.5.3
  - conda-forge::r-r6=2.4.1
  - conda-forge::r-clipr=0.7.0
  - conda-forge::r-crayon=1.3.4
  - conda-forge::r-bh=1.72.0_3
  - conda-forge::r-pbapply=1.4_3
  - conda-forge::r-iotools=0.3_1
  - conda-forge::r-readr=1.3.1
  - conda-forge::r-seqminer=8.0

**Comment by victorrenault** [comment]
Hi @FriederikeHanssen ,

I will try to have a version ready by the end of the month. I will notify you when it is ready.

Cheers

**Comment by FriederikeHanssen** [comment]
@victorrenault Awesome! Thank you 👍 😊
